name: base
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - archspec=0.2.1
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - conda=24.1.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=23.12.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - cryptography=41.0.7
  - distro=1.8.0
  - expat=2.5.0
  - fmt=9.1.0
  - icu=73.1
  - idna=3.4
  - jsonpatch=1.32
  - jsonpointer=2.1
  - krb5=1.20.1
  - ld_impl_linux-64=2.38
  - libarchive=3.6.2
  - libcurl=8.5.0
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libmamba=1.5.3
  - libmambapy=1.5.3
  - libnghttp2=1.57.0
  - libsolv=0.7.24
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxml2=2.10.4
  - lz4-c=1.9.4
  - menuinst=2.0.2
  - ncurses=6.4
  - openssl=3.0.13
  - packaging=23.1
  - pcre2=10.42
  - pip=23.3.1
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.1
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.31.0
  - ruamel.yaml=0.17.21
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tqdm=4.65.0
  - truststore=0.8.0
  - tzdata=2023d
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.5
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.19.0
  - zstd=1.5.5
